namespace TruthWeaver.Generators;

/// <summary>
/// The source of the <c>[Predicate]</c> attribute. The generator adds it to every consuming compilation, so the
/// package needs no run-time assembly.
/// </summary>
internal static class PredicateAttributeSource
{
    /// <summary>The metadata name the generator looks for.</summary>
    public const string MetadataName = "TruthWeaver.Generators.PredicateAttribute";

    /// <summary>The hint name of the generated attribute file.</summary>
    public const string HintName = "TruthWeaver.Generators.PredicateAttribute.g.cs";

    /// <summary>
    /// The attribute source. <c>[Embedded]</c> keeps the type invisible to other compilations, so two projects that
    /// both use the generator and share internals do not get two conflicting attribute types. <c>[Conditional]</c>
    /// keeps the attribute out of the compiled assembly: the generator reads it from source.
    /// </summary>
    public const string Text = """
        // <auto-generated/>
        #nullable enable

        namespace TruthWeaver.Generators
        {
            /// <summary>
            /// Marks a static predicate method for registration. The TruthWeaver.Generators source generator builds the
            /// predicate schema from the method signature and emits a <c>Register</c> method on the containing type.
            /// </summary>
            /// <remarks>
            /// <para>
            /// The first parameter is the application context. A <see cref="global::System.Threading.CancellationToken"/>
            /// parameter receives the cancellation token of the evaluation. Every other parameter is a rule argument with
            /// the parameter name: <see cref="string"/>, <see cref="long"/>, <see cref="decimal"/>, <see cref="bool"/>,
            /// <see cref="global::System.DateTimeOffset"/>, <see cref="global::System.Guid"/>, or an
            /// <see cref="global::System.Collections.Generic.IReadOnlyList{T}"/> of one of them. A parameter with a default
            /// value is an optional argument. The <c>param</c> documentation comment is the argument description.
            /// </para>
            /// <para>
            /// The method returns <c>TruthValue</c>, <c>ValueTask&lt;TruthValue&gt;</c> or <c>Task&lt;TruthValue&gt;</c>.
            /// </para>
            /// </remarks>
            [global::Microsoft.CodeAnalysis.Embedded]
            [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
            [global::System.Diagnostics.Conditional("TRUTHWEAVER_GENERATORS_KEEP_ATTRIBUTES")]
            internal sealed class PredicateAttribute : global::System.Attribute
            {
                /// <summary>Initializes a new instance of the <see cref="PredicateAttribute"/> class.</summary>
                /// <param name="name">The registered predicate name, as rule text writes it.</param>
                /// <param name="label">A short display name for the predicate.</param>
                /// <param name="description">What the predicate answers.</param>
                public PredicateAttribute(string name, string label, string description)
                {
                    this.Name = name;
                    this.Label = label;
                    this.Description = description;
                }

                /// <summary>Gets the registered predicate name.</summary>
                public string Name { get; }

                /// <summary>Gets the display name.</summary>
                public string Label { get; }

                /// <summary>Gets the description.</summary>
                public string Description { get; }
            }
        }

        """;
}
