namespace TruthWeaver.Generators;

using Microsoft.CodeAnalysis.CSharp;
using TruthWeaver.Generators.Model;

/// <summary>
/// Writes the <c>Register</c> methods of one containing type: one overload per context type. Each method adds every
/// predicate of that context type to a <c>PredicateRegistryBuilder</c> through its public <c>Add</c> method.
/// </summary>
internal static class RegisterEmitter
{
    private const string Abstractions = "global::TruthWeaver.Abstractions.";
    private const string TruthValueTask = "global::System.Threading.Tasks.ValueTask<" + Abstractions + "TruthValue>";

    /// <summary>Writes the generated file for one containing type.</summary>
    /// <param name="type">The containing type.</param>
    /// <param name="methods">The valid predicate methods of the type, in source order.</param>
    /// <returns>The source text.</returns>
    public static string Emit(ContainingType type, IReadOnlyList<PredicateMethod> methods)
    {
        CodeWriter writer = new();
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();

        if (type.Namespace.Length > 0)
        {
            writer.Open("namespace " + type.Namespace);
        }

        foreach (string declaration in type.Declarations)
        {
            writer.Open(declaration);
        }

        bool first = true;
        foreach (IGrouping<string, PredicateMethod> group in methods.GroupBy(m => m.ContextType, StringComparer.Ordinal))
        {
            if (!first)
            {
                writer.Line();
            }

            first = false;
            EmitRegister(writer, group.Key, group.All(m => m.ContextIsPublic), [.. group]);
        }

        for (int index = 0; index < type.Declarations.Count; index++)
        {
            writer.Close();
        }

        if (type.Namespace.Length > 0)
        {
            writer.Close();
        }

        return writer.ToString();
    }

    private static void EmitRegister(
        CodeWriter writer,
        string contextType,
        bool isPublic,
        IReadOnlyList<PredicateMethod> methods
    )
    {
        string builderType = "global::TruthWeaver.Registry.PredicateRegistryBuilder<" + contextType + ">";

        // A public method may not expose an internal context type (CS0051), so the method follows the context type.
        string accessibility = isPublic ? "public" : "internal";

        writer.Line("/// <summary>");
        writer.Line(
            "/// Adds the predicates of this type that read <c>"
                + XmlText(contextType)
                + "</c> to <paramref name=\"builder\"/>."
        );
        writer.Line("/// The TruthWeaver.Generators source generator writes this method from the <c>[Predicate]</c> methods.");
        writer.Line("/// </summary>");
        writer.Line("/// <param name=\"builder\">The registry builder to add the predicates to.</param>");
        writer.Line("/// <returns><paramref name=\"builder\"/>, for chaining.</returns>");
        writer.Line("[global::System.CodeDom.Compiler.GeneratedCode(\"TruthWeaver.Generators\", \"1.0.0\")]");
        writer.Open(accessibility + " static " + builderType + " Register(" + builderType + " builder)");
        writer.Open("if (builder is null)");
        writer.Line("throw new global::System.ArgumentNullException(nameof(builder));");
        writer.Close();
        writer.Line();

        foreach (PredicateMethod method in methods)
        {
            EmitAdd(writer, method);
        }

        writer.Line("return builder;");
        writer.Close();
    }

    private static void EmitAdd(CodeWriter writer, PredicateMethod method)
    {
        writer.Line("builder.Add(");
        writer.Indent();
        writer.Line("new " + Abstractions + "PredicateSchema(");
        writer.Indent();
        writer.Line(Literal(method.PredicateName) + ",");
        writer.Line(Literal(method.Label) + ",");
        writer.Line(Literal(method.Description) + ",");
        writer.Line("new " + Abstractions + "PredicateArgumentSchema[]");
        writer.Open(string.Empty);
        foreach (PredicateParameter argument in method.Parameters.Where(p => p.Role == ParameterRole.Argument))
        {
            string required = argument.Default is null ? "true" : "false";
            string defaultValue = argument.Default ?? "null";
            writer.Line(
                "new "
                    + Abstractions
                    + "PredicateArgumentSchema("
                    + Literal(argument.Name)
                    + ", "
                    + Literal(argument.Description)
                    + ", "
                    + Abstractions
                    + "LiteralKind."
                    + argument.Kind
                    + ", "
                    + required
                    + ", "
                    + defaultValue
                    + "),"
            );
        }

        writer.Dedent();
        writer.Line("}),");
        writer.Dedent();
        writer.Line("static (context, arguments, cancellationToken) => " + Invocation(method) + ");");
        writer.Dedent();
        writer.Line();
    }

    private static string Invocation(PredicateMethod method)
    {
        IEnumerable<string> arguments = method.Parameters.Select(p =>
            p.Role switch
            {
                ParameterRole.Context => "context",
                ParameterRole.CancellationToken => "cancellationToken",
                _ => "arguments." + Getter(p.Kind) + "(" + Literal(p.Name) + ")",
            }
        );
        string call = method.MethodName + "(" + string.Join(", ", arguments) + ")";
        return method.Return switch
        {
            ReturnShape.ValueTask => call,
            _ => "new " + TruthValueTask + "(" + call + ")",
        };
    }

    /// <summary>Names the <c>PredicateArguments</c> getter for a literal kind, for example <c>GetInt64Array</c>.</summary>
    private static string Getter(string kind)
    {
        // The getters follow the LiteralKind names, except that Boolean is shortened to Bool.
        return "Get" + kind.Replace("Boolean", "Bool");
    }

    private static string Literal(string value)
    {
        return SymbolDisplay.FormatLiteral(value, true);
    }

    private static string XmlText(string fullyQualifiedType)
    {
        return fullyQualifiedType
            .Replace("global::", string.Empty)
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }
}
